#yml文件中， ：后面一定要加空格 不然读值有误

server:
  port: 8080

film:
  img-pre: http://img.catfilm.com/

order-file:
  file-pre: F:/deploy_project/catFilm/resources
  alipay-callBack: http://catfilmlgw.natapp1.cc/order/alipay/callback
jwt:
  header: Authorization   #http请求头所需要的字段 key字段
  secret: mySecret        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  md5-key: randomKey      #md5加密混淆key

rest:
  auth-open: true    #true 表示开始过滤检查jwt

mybatis-plus:
  mapper-locations: classpath*:com/catfilm/springboot/**/xml/*Mapper.xml
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cat_film?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    filters: log4j,wall,mergeStat


logging:
  level.root: info
  level.com.catfilm.springboot: debug
  path: logs/
  file: cat-film.log
